name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional, for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Run the build and publish script
      - name: Build and Publish Docker Image
        run: |
          chmod +x ./build_and_publish.sh
          ./build_and_publish.sh

  deploy:
    needs: build-and-publish  # Run after build-and-publish job
    runs-on: ubuntu-latest
    steps:
      # Checkout code (optional, if needed for scripts)
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/bots
            docker compose pull
            docker compose down suggestionsbot
            docker compose up --force-recreate -d suggestionsbot
